// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef start_h
#define start_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Choice.H>

class ParameterGUI {
public:
  ParameterGUI();
  static Fl_Menu_Item menu_bar[];
  static Fl_Menu_Item menu_menu[];
  static Fl_Menu_Item menu_choice[];
};
#endif
