// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "text.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(860, 355);
    w = o;
    { new Fl_Adjuster(160, 125, 170, 45, "bla");
    } // Fl_Adjuster* o
    { Fl_Choice* o = new Fl_Choice(350, 30, 200, 80, "a;b;c");
      o->tooltip("bla");
      o->down_box(FL_BORDER_BOX);
    } // Fl_Choice* o
    { Fl_Pack* o = new Fl_Pack(15, 155, 860, 105);
      { Fl_Roller* o = new Fl_Roller(80, 155, 795, 65, "roll");
        o->type(1);
        o->align(FL_ALIGN_CENTER);
      } // Fl_Roller* o
      { Fl_Dial* o = new Fl_Dial(15, 155, 50, 105);
        o->type(1);
      } // Fl_Dial* o
      o->end();
    } // Fl_Pack* o
    { Fl_Tile* o = new Fl_Tile(615, 125, 200, 185);
      { Fl_Value_Slider* o = new Fl_Value_Slider(785, 200, 30, 110);
        o->type(4);
      } // Fl_Value_Slider* o
      { new Fl_Button(615, 125, 25, 25, "OK");
      } // Fl_Button* o
      o->end();
    } // Fl_Tile* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
