BASE = ../..

OBJS = main.o
PLIB = 1
DEPEND = Core System Hardware_joystick Motion Ors Gui pr2

LPATHS += /opt/ros/groovy/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/gofMake/generic.mk
