BASE = ../../../share

OBJS = main.o $(BASE)/teaching/RoboticsPractical/interface/myBaxter.o

ROS = 1
DEPEND = Core Geo Control Gui RosCom Hardware_gamepad Kin Motion Actions

include $(BASE)/gofMake/generic.mk

