BASE = ../..
# OBJS = main.o

REALCAMERA=1
# ANN = 1
# #TONY = 1
# OPENCV = 1
# SCHUNK = 1
# #ODE = 1
# QHULL = 1
# FREEGLUT = 1
# SWIFT = 1
# LAPACK = 1
# PLIB = 1
# BUMBLE = 1
# #URGLASER = 1
# CUDA = 1
# #REVEL = 1
# LEWINER = 1
# buildAndLink_NIKOLAY = 1
# buildAndLink_TOBIAS = 1
# buildAndLink_NILS = 1

include $(BASE)/gofMake/make-generic

