BASE = ../../../../share

OBJS = main.o src/mb_strategy.o ../../src/traj_factory.o ../../src/task_grasp.o ../../src/task_door.o ../../src/task_button.o ../../src/plotUtil.o
DEPEND = Core Ors Gui Algo Motion Optim pr2 Geo
PTHREAD = 0
PHYSX = 0
ROS = 1

include $(BASE)/gofMake/generic.mk
