BASE   = ../../..
NAME   = libHardware_$(shell basename `pwd`)
OUTPUT = ../$(NAME).so

DEPEND = Core Ors Gui Mocap

G4 = 1

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/build/generic.mk
