BASE = ../..
OBJS = main.o

CXXFLAGS += -DMT_IMPLEMENT_TEMPLATES

###buildAndLink_MTLIB = 1
###OPENCV = 1

buildAndLink_MTLIB = 1
ANN = 1
#TONY = 1
OPENCV = 1
SCHUNK = 1
#ODE = 1
QHULL = 1
FREEGLUT = 1
SWIFT = 1
LAPACK = 1
PLIB = 1
BUMBLE = 1
#URGLASER = 1
CUDA = 1
#REVEL = 1
LEWINER = 1
buildAndLink_NIKOLAY = 1
buildAndLink_RELATIONAL = 1
buildAndLink_NILS = 1

include $(BASE)/make-generic
