BASE = $(shell pwd)/../../../share
OBJS = main.o

STANIMIR = 1
DMITRY = 1

CXXFLAGS += -fPIC -DMLR_IMPLEMENT_TEMPLATES #causes all *.cpp to implement the used templates

include $(BASE)/build/generic.mk

