option(WITH_FREENECT "Use libfreenect for Kinect" ON)
if(WITH_FREENECT)
    include(FindPkgConfig)
    pkg_check_modules(LIBFREENECT libfreenect)
    if(LIBFREENECT_FOUND)
     add_definitions(-DMLR_FREENECT)
    endif()
else(WITH_FREENECT)
    message(STATUS "Kinect support disabled")
    unset(LIBFREENECT_FOUND CACHE)
endif(WITH_FREENECT)
