BASE = ../..

ROS = 1
PLIB = 1
PCL = 1
GL = 1
DEPEND = Core Geo Hardware_gamepad Motion Ors Gui RosCom Perception

LPATHS += /opt/ros/indigo/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/gofMake/generic.mk
