BASE = ../..

ROS = 1
PLIB = 1
PCL = 1
GL = 1
DEPEND = Core System Hardware_gamepad Motion Ors Gui pr2 Perception

LPATHS += /opt/ros/groovy/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/gofMake/generic.mk
