BASE = ../../../../share

OBJS = main.o ../12_MBMF_LEARNING/task_manager.o ../src/traj_factory.o ../17_FINAL/src/motion_interface.o
DEPEND = Core Ors Gui Algo Motion Optim System pr2 Hardware_gamepad Actions
PTHREAD = 0
PHYSX = 0
include $(BASE)/gofMake/generic.mk
