BASE = ../../..

DEPEND = Motion Core Geo Ors Gui Optim Algo
GL = 1
LIBS += -lGL
include $(BASE)/build/generic.mk


# OUTPUTLIB = ../$(NAME).so
# SRCSLIB = mobject.cpp pfc.cpp
# OBJSLIB = $(SRCSLIB:%.cpp=%.o)
# lib: $(OUTPUTLIB) $(SRCSLIB) $(OBJSLIB)
