BASE = ../..
OBJS = main.o

CXXFLAGS += -DMT_IMPLEMENT_TEMPLATES

buildAndLink_MTLIB = 1
###OPENCV = 1

PCL=1
OPENCV= 1

LIBS += -lstdc++ -lbiros -lhardware -lperception -ljk -lrelational -lmotion -lm

buildAndLink_MTLIB = 1

include $(BASE)/make-generic
