BASE = ../..
OBJS = main.o

CXXFLAGS += -DMT_IMPLEMENT_TEMPLATES

###buildAndLink_MTLIB = 1
###OPENCV = 1

PCL=1

LIBS += -lbiros -lhardware -lperception -ljk -lrelational -lmotion

buildAndLink_MTLIB = 1

include $(BASE)/make-generic
