BASE = ../../../../share


OBJS = main.o taskMapVariance.o
PLIB = 1
ROS = 1
DEPEND = Core RosCom Control Gui Actions Hardware_gamepad Ors Motion Geo Roopi Algo Optim

include $(BASE)/gofMake/generic.mk
