BASE = ../../..

PLIB = 1

OBJS = main.o g4taprecon/taprecon.o g4mapper/calibrator_module.o
DEPEND = Core System Hardware_gamepad Hardware_G4 Motion Ors Perception Mocap Gui

# comment/uncomment to disable/enable ROS
# ROS = 1
# ROS_VERSION = groovy
# CXXFLAGS = -DWITH_ROS
# DEPEND += pr2 Actions
# LPATHS += /opt/ros/groovy/lib

include $(BASE)/gofMake/generic.mk
