BASE = ../..

# buildAndLink_HARDWARE = 1
# buildAndLink_PCL = 1
# LIBS += -lhardware -lperception -lbiros -lvtkCommon -lvtkFiltering -lvtkRendering -ldevTools

DEPEND = hardware

include $(BASE)/make-generic
