BASE   = ../../..
NAME   = libSystem_$(shell basename `pwd`)
OUTPUT := $(BASE)/lib/$(NAME).so

ROS = 1
DEPEND = Core System 

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

CPATHS += $(BASE)/projects/marc_controller_pkg/msg_gen/cpp/include $(BASE)/projects/marc_controller_pkg/srv_gen/cpp/include

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
