BASE = ../../../../../share

OBJS = main.o ../../src/traj_factory.o  ../src/task_door.o ../../src/plotUtil.o
DEPEND = Core Kin Gui Algo KOMO Optim pr2 Hardware_gamepad Actions Geo
PTHREAD = 0
PHYSX = 0

include $(BASE)/build/generic.mk
