BASE = ../../../../share

OBJS = main.o ../../src/motion_factory.o ../../src/traj_factory.o ../../src/cost_weight.o ../../src/inverse_motion.o ../../src/scene.o
DEPEND = Core Motion Gui Optim Algo Ors Geo pr2
PTHREAD = 1
PHYSX = 1
include $(BASE)/build/generic.mk
