# Symbol grounding Makefile
# Johannes, 09 Dec 2011
#

BASE = ../../../share

LIBS += -lrelational -lMT -lbiros -ljk -lstdc++
CXXFLAGS += -DMT_IMPLEMENT_TEMPLATES
CUDA = 0
OBJS  = main.o 

include $(BASE)/gofMake/generic.mk
