BASE = ../../../share

OPTIM = fast

OBJS = main.o $(BASE)/src/MT/vision_cuda.o

CXXFLAGS += -DMT_NO_GLOBALMEM

LAPACK = 1
OPENCV = 1
VISION = 1
FREEGLUT=1
BUMBLE = 1
NILS = 1
CUDA = 1
SWIFT = 1
SCHUNK = 1
PLIB = 1  #for the Joystick

include $(BASE)/gofMake/generic.mk



