set(SOURCES ./ors_physx.h
./ors_oldTaskVariables.cpp
./roboticsCourse.h
./ors_blender.cpp
./roboticsCourse.cpp
./ors_featherstone.cpp
./ors_tutorial.h
./ors_ode.h
./ors_opengl.cpp
./ors_actionInterface.cpp
./ors_sceneGui.h
./ors_sceneGui.cpp
./module_G4Display.h
./ors.cpp
./ors.h
./ors_swift.h
./module_G4Display.cpp
./ors_actionInterface.h
./ors_swift.cpp
./ors_physx.cpp
./ors_ode.cpp
./ors_oldTaskVariables.h)
