BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = ../$(NAME).so

LAPACK = 1
#OPTIM=fast_debug

DEPEND = FOL Motion

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/build/generic.mk
