BASE = ../../share

PCL = 1

buildAndLink_HARDWARE = 1
LIBS += -lmotion -lhardware -lperception -lbiros -lvtkCommon -lvtkFiltering -lvtkRendering -lstdc++ -lm -lvtkGraphics

include $(BASE)/make-generic
