set(SOURCES ./registry.h
./tests.cpp
./geo.h
./keyValueGraph_t.h
./module.h
./keyValueGraph.cpp
./core.cpp
./module_FloatA_Recorder.cpp
./registry.cpp
./thread.cpp
./array_lapack.cpp
./cygwin_compat.h
./geo.cpp
./array.h
./thread.h
./util_t.h
./keyValueGraph.h
./module.cpp
./util.cpp
./array_t.h
./array.cpp
./util.h
./module_FloatA_Recorder.h)
