set(SOURCES ./module_FloatA_Recorder.h
./geo.h
./module_FloatA_Recorder.cpp
./tests.cpp
./module.h
./registry.h
./keyValueGraph.cpp
./array_lapack.cpp
./util_t.h
./core.cpp
./cygwin_compat.h
./util.h
./array_t.h
./keyValueGraph.h
./array.cpp
./keyValueGraph_t.h
./registry.cpp
./module.cpp
./geo.cpp
./array.h
./thread.cpp
./thread.h
./util.cpp)
