BASE = ../../../../share

OBJS = main.o ../17_FINAL/src/motion_interface.o ../17_FINAL/src/task_door.o ../src/traj_factory.o ../src/plotUtil.o
DEPEND = Core Kin Gui Algo KOMO Optim System Hardware_gamepad Actions pr2
PTHREAD = 0
PHYSX = 0
ROS = 1
include $(BASE)/build/generic.mk
