BASE = ../..


OBJS = main.o
PLIB = 1
ROS = 1
DEPEND = Core System Hardware_gamepad Motion Ors Gui pr2

LPATHS += /opt/ros/groovy/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/gofMake/generic.mk
