BASE = ../..


OBJS = main.o
PLIB = 1
ROS = 1
DEPEND = Geo Optim Core Hardware_gamepad Motion Ors Gui RosCom

CPATHS += ../../../../../rosbuild_ws/sandbox/articulation/articulation_models/include/
CPATHS += ../../../../../rosbuild_ws/sandbox/articulation/articulation_msgs/msg_gen/cpp/include/
LPATHS += ../../../../../rosbuild_ws/sandbox/articulation/articulation_models/lib/
LIBS += -larticulation_models


include $(BASE)/gofMake/generic.mk
