BASE = $(shell pwd)/../../..

DEPEND = Core MDP

OBJS = main.o

LAPACK = 1
QT = 1## comment this line if you don't want to compile the GUI

default: mdp.exe

OBJS := gui_moc.o $(OBJS)
gui_moc.o: gui_ui.h gui_moc.cpp

CLEAN = *_moc.cpp *_ui.h MT.log

include $(BASE)/gofMake/make-generic

