BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = ../$(NAME).so

DEPEND = Core

SRC_CPP = $(shell find . -maxdepth 1 -name '*.cpp')
SRC_C   = $(shell find . -maxdepth 1 -name '*.c')
SRCS = $(SRC_CPP) $(SRC_C)
OBJS = $(SRC_CPP:%.cpp=%.o) $(SRC_C:%.c=%.o)

include $(BASE)/build/generic.mk
