BASE   = ../../..
NAME   = libHardware_$(shell basename `pwd`)
OUTPUT := $(BASE)/lib/$(NAME).so

PLIB = 1
DEPEND = Core

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
