BASE = ../../../../share

OBJS = main.o ../12_MBMF_LEARNING/task_manager.o ../src/traj_factory.o ../12_MBMF_LEARNING/mf_strategy.o
DEPEND = Core Kin Gui Algo KOMO Optim System pr2 Hardware_gamepad Actions
PTHREAD = 0
PHYSX = 0
include $(BASE)/build/generic.mk
