BASE = ../..

OBJS = main.o methods.o plane.o dataStructures.o object_detector.o object.o ros.o

PCL = 1
ROS = 1
GL = 1
DEPEND = Core Hardware_kinect Perception Gui Kin RosCom
LIBS += -lboost_system

include $(BASE)/build/generic.mk
