BASE = ../..

OBJS = main.o methods.o plane.o dataStructures.o object_detector.o object.o

PCL = 1
ROS = 1
GL = 1
DEPEND = Core System Hardware_kinect Perception Gui Ors pr2
LIBS += -lboost_system

include $(BASE)/gofMake/generic.mk
