BASE = ../..
# NAME   = 

DEPEND = Core
# OUTPUT = x.exe rosmsgs
ROS = 1

include $(BASE)/build/generic.mk

# MSGFILE = msg/Literal.msg

# rosmsgs:
# 	python2 /opt/ros/$(ROS_DISTRO)/lib/gencpp/gen_cpp.py \
# 	$(MSGFILE) \
# 	-p $(shell basename `pwd`) \
# 	-e /opt/ros/$(ROS_DISTRO)/share/gencpp \
# 	-I "std_msgs:/opt/ros/$(ROS_DISTRO)/share/std_msgs/msg" \
# 	-o $(BASE)/include/ros_msg\
	
# 	python2 /opt/ros/$(ROS_DISTRO)/share/rospy/rosbuild/scripts/genmsg_py.py --noinitpy \
# 	$(MSGFILE)\
	
# 	python2 /opt/ros/$(ROS_DISTRO)/share/rospy/rosbuild/scripts/genmsg_py.py --initpy \
# 	$(MSGFILE)





