BASE = ../../../../share

OBJS = main.o ../src/phase_optimization.o ../src/traj_factory.o mb_strategy.o mf_strategy.o motion_interface.o mbmfl.o task_manager.o
DEPEND = Core Kin Gui Algo Motion Optim System pr2 Hardware_gamepad Actions
PTHREAD = 0
PHYSX = 0
include $(BASE)/build/generic.mk
