BASE = ../../..

QT = 1
CXXFLAGS += -D__STDC_CONSTANT_MACROS
LPATHS += /usr/local/lib
LIBS += -lavformat -lavcodec -lavutil -lswscale -lx264 -lz

OBJS = main.o
DEPEND = Core Hardware_VideoWriter

include $(BASE)/make-generic
