BASE = ../../../share

//GTK = 1

#CPATH	:= $(HOME)/tmp/gvd/include:$(CPATH)
#LPATH	:= $(HOME)/tmp/gvd/lib:$(LPATH)

#CXXFLAGS += -DMLR_IMPLEMENT_TEMPLATES

#LIBS += -lgraph -lgvc

include $(BASE)/build/generic.mk
