BASE = ../../../../../share

OBJS = main.o ../../src/phase_optimization.o ../src/motion_interface.o ../src/task_manager.o ../../src/plotUtil.o ../../src/traj_factory.o
DEPEND = Core Ors Gui Algo Motion Optim System pr2 Hardware_gamepad Actions
PTHREAD = 0
PHYSX = 0
include $(BASE)/gofMake/generic.mk
