BASE = $(shell pwd)/../../../share

#OBJ = gui_moc.o main.o
OBJS = main.o

#gui_moc.o: gui_moc.cpp schunkMonitor_ui.h

#CXXFLAGS += -DMT_QTGLUT

FREEGLUT = 1
#SWIFT = 1
#LAPACK = 1
#QT = 1
#SCHUNK = 1
#PLIB = 1
URGLASER = 1

CLEAN = *_moc.cpp *_ui.h MT.log

include $(BASE)/gofMake/generic.mk

