BASE   = $(shell realpath .)
NAME   = $(shell basename $(BASE))

ALL =	extern/SWIFT++_1.2/src \
	src/MT
#	extern/SWIFT++_1.2/decomposer/src \

makeAll: $(ALL:%=makePath/%) makeSubpaths/test makeSubpaths/course

cleanAll: $(ALL:%=cleanPath/%) cleanSubpaths/test cleanSubpaths/course

include gofMake/generic.mk