BASE = ../..

OBJS = main.o roscom.o puppeteer.o
PLIB = 1
ROS = 1
DEPEND = Core System Hardware

CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

CPATHS += ../marc_controller_pkg/msg_gen/cpp/include ../marc_controller_pkg/srv_gen/cpp/include

DEPEND = Core Hardware_joystick Motion Ors Gui System

include $(BASE)/gofMake/generic.mk
