BASE = ../..

OBJS = main.o dataStructures.o methods.o

PCL = 1
ROS = 1
GL = 1
DEPEND = Core System Hardware_kinect Perception Gui Ors pr2 Hardware_gamepad
LIBS += -lboost_system

include $(BASE)/gofMake/generic.mk
