BASE = ../../../../share

OBJS = main.o ../src/ikmo.o ../src/motion_factory.o ../src/gaussian_costs.o ../src/rbf_costs.o
DEPEND = Core Motion Gui Optim Algo Ors
PTHREAD = 1
PHYSX = 1
include $(BASE)/gofMake/generic.mk
