#! /usr/bin/python
import os

num_iter = 10
num_attempts = 10
num_clusters = 250

cmd1 = "../src/texturedesc2block.exe -i ../data/files.list -o ../data/block.surf.array"
cmd2 = "../src/block2codebook.exe -i ../data/block.surf.array -o ../data/ -c %i -a %i -e %i" % (num_clusters, num_attempts, num_iter)
os.system(cmd1)
os.system(cmd2)
print "done"
