#! /usr/bin/python

# test script for the generation of color descriptors

import os

files = ["2007_000032",
         "2007_000033",
         "2007_000039",
         "2007_000042",
         "2007_000061",
         "2007_000063",
         "2007_000068",
         "2007_000121",
         "2007_000123",
         "2007_000129",
         "2007_000170",
         "2007_000175",
         "2007_000187",
         "2007_000241",
         "2007_000243",
         "2007_000250",
         "2007_000256",
         "2007_000323",
         "2007_000332",
         "2007_000333"]

# number of bins for color descriptors
num_coef = 25

for file_cur in files:
  cmd = "../src/tree_final_features.exe -t ../data/%s.texturehist.array -c ../data/%s.colordesc.array -s ../data/%s.shapedesc.array -u ../data/%s.tree.array  -o ../data/%s.features.array" % (file_cur, file_cur, file_cur, file_cur, file_cur)
  print cmd
  os.system(cmd)

