BASE = ../../../../../share

OBJS = main.o ../src/motion_interface.o ../src/mb_strategy.o ../../src/traj_factory.o ../src/task_manager.o ../../src/plotUtil.o
DEPEND = Core Ors Gui Algo Motion Optim System Hardware_gamepad Actions pr2
PTHREAD = 0
PHYSX = 0
ROS = 1
include $(BASE)/gofMake/generic.mk
