BASE = ../../../../share

OBJS = main.o ../src/motion_factory.o ../src/cost_weight.o ../src/inverse_motion.o ../src/scene.o
DEPEND = Core Motion Gui Optim Algo Ors
PTHREAD = 1
PHYSX = 1
include $(BASE)/gofMake/generic.mk
