BASE = ../../../../share

OBJS = main.o ../src/motion_factory.o ../src/cost_weight.o ../src/inverse_motion.o ../src/scene.o
DEPEND = Core KOMO Gui Optim Algo Kin
PTHREAD = 1
PHYSX = 1
include $(BASE)/build/generic.mk
