#include "util.h"

void MTforceImplementations(){
  MT::getParameter<long>("bla");
}

#if 0
//#include "algos.h"
#include "MT/array.h"
#include "MT/array_t.cpp"
//#include "BinaryBP.h"
//#include "BinaryBPModel.h"
//#include "cudaModules.h"
//#include "daiModule.h"
//#include "data.h"
//#include "earlyVisionModule.h"
//#include "functions.h"
//#include "gauss.h"
#include "gaussianProcess.h"
#include "graspObjects.h"
#include "guiModule.h"
//#include "infer.h"
//#include "joystick.h"
//#include "mdp_EMSolver.h"
//#include "mdp.h"
//#include "mexmagic.h"
//#include "motionPlannerModule.h"
//#include "mstep.h"
#include "opengl.h"
#include "optimization.h"
//#include "ors_actionInterface.h"
#include "ors.h"
#include "perceptionModule.h"
#include "plot.h"
//#include "revelModule.h"
#include "robot.h"
//#include "robot_marcTask.h"
#include "schunk.h"
#include "soc.h"
#include "specialTaskVariables.h"
#include "threads.h"
#include "truncatedGaussian.h"
#include "util.h"
//#include "vision_cuda.h"
//#include "vision.h"
#endif
