# TODO MUSS NOCH ANGEPASST WERDEN
# Tobias, 7 Nov 11

BASE = ../../share

# OBJS = main.o \
# 	symbolGrounding.o

RELATIONAL = 1
#ODE = 1
FREEGLUT = 1
SWIFT   = 1
QHULL   = 1

include $(BASE)/make-generic


