# TODO MUSS NOCH ANGEPASST WERDEN
# Tobias, 7 Nov 11

BASE = ../../share

# OBJS = main.o \
# 	$(BASE)/src/MT/array_instantiate.o \
# 	$(BASE)/src/MT/array_t.o

RELATIONAL = 1
#ODE = 1
FREEGLUT = 1
SWIFT   = 1
QHULL   = 1

include $(BASE)/make-generic


