set(SOURCES ./pointcloud.h
./opencv.h
./perception.h
./keyframe.h
./avutil.h
./opencv.cpp
./video_opencv.cpp
./libcolorseg.h
./colorspace.cpp
./videoEncoder.h
./g4data.h
./audio.h
./pointcloud.cpp
./perception.cpp
./keyframe.cpp
./keyframer.cpp
./avutil.cpp
./colorspace.h
./shapeFitter.h
./shapeFitter.cpp
./libcolorseg.cpp
./audio.cpp
./videoEncoder.cpp
./g4data.cpp
./perception_views.cpp
./keyframer.h
./videoEncoderX264.cpp
./vision.h)
