BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT := $(BASE)/lib/$(NAME).so

#OPTIM=fast
GL = 1
LAPACK = 1
OPENCV = 1
#PCL = 1
X264 = 0
DEPEND = Core Gui extern_libcolorseg Ors


#CXXFLAGS += -D__STDC_CONSTANT_MACROS -DHAVE_LIBAV
#LIBS += -lavformat -lavcodec -lavutil -lswscale -lx264 -lz
CXXFLAGS += -Wno-unknown-pragmas

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
