/* Auto-generated by genmsg_cpp for file /home/bais/git/mlr/share/projects/RelationalMachine/msg/ActionCommandResult.msg */
#ifndef RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDRESULT_H
#define RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace RelationalMachine
{
template <class ContainerAllocator>
struct ActionCommandResult_ {
  typedef ActionCommandResult_<ContainerAllocator> Type;

  ActionCommandResult_()
  : result()
  {
  }

  ActionCommandResult_(const ContainerAllocator& _alloc)
  : result(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  result;


  typedef boost::shared_ptr< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RelationalMachine::ActionCommandResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ActionCommandResult
typedef  ::RelationalMachine::ActionCommandResult_<std::allocator<void> > ActionCommandResult;

typedef boost::shared_ptr< ::RelationalMachine::ActionCommandResult> ActionCommandResultPtr;
typedef boost::shared_ptr< ::RelationalMachine::ActionCommandResult const> ActionCommandResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::RelationalMachine::ActionCommandResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace RelationalMachine

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::RelationalMachine::ActionCommandResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "RelationalMachine/ActionCommandResult";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
string result # conv, timeout, fail\n\
\n\
";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ActionCommandResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RelationalMachine::ActionCommandResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::RelationalMachine::ActionCommandResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDRESULT_H

