/* Auto-generated by genmsg_cpp for file /home/bais/git/mlr/share/projects/RelationalMachine/msg/ActionCommandFeedback.msg */
#ifndef RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDFEEDBACK_H
#define RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace RelationalMachine
{
template <class ContainerAllocator>
struct ActionCommandFeedback_ {
  typedef ActionCommandFeedback_<ContainerAllocator> Type;

  ActionCommandFeedback_()
  : percentage_complete(0.0)
  {
  }

  ActionCommandFeedback_(const ContainerAllocator& _alloc)
  : percentage_complete(0.0)
  {
  }

  typedef float _percentage_complete_type;
  float percentage_complete;


  typedef boost::shared_ptr< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ActionCommandFeedback
typedef  ::RelationalMachine::ActionCommandFeedback_<std::allocator<void> > ActionCommandFeedback;

typedef boost::shared_ptr< ::RelationalMachine::ActionCommandFeedback> ActionCommandFeedbackPtr;
typedef boost::shared_ptr< ::RelationalMachine::ActionCommandFeedback const> ActionCommandFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace RelationalMachine

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e59a2842413d60206f458c042f7cfd36";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe59a2842413d6020ULL;
  static const uint64_t static_value2 = 0x6f458c042f7cfd36ULL;
};

template<class ContainerAllocator>
struct DataType< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "RelationalMachine/ActionCommandFeedback";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 percentage_complete\n\
\n\
\n\
";
  }

  static const char* value(const  ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.percentage_complete);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ActionCommandFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::RelationalMachine::ActionCommandFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "percentage_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percentage_complete);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RELATIONALMACHINE_MESSAGE_ACTIONCOMMANDFEEDBACK_H

