BASE = ../..

FREEGLUT = 1

# \
# -lSceneQuery \
# -lLowLevelCloth \
# -lPhysX3Extensions \
# -lPhysX3Cooking \
# -lPhysX3Vehicle \
# -lRepXUpgrader3 \
# -lPhysXProfileSDK \
# -lRepX3 \
# -lPvdRuntime \
# -lPhysX3Common \
# -lPhysX3 \
# -lPhysXVisualDebuggerSDK \
# -lSimulationController \
# -lPxTask \
# -lPhysX3CharacterKinematic \
# -lLowLevel \
# -lpthread \

include $(BASE)/make-generic