BASE = ../../../../share

OBJS = main.o ../../src/traj_factory.o ../../src/task_button.o ../../src/plotUtil.o ../../src/motion_factory.o ../../src/cost_weight.o ../../src/inverse_motion.o ../../src/scene.o
DEPEND = Core KOMO Gui Optim Algo Kin Geo
PTHREAD = 1
PHYSX = 1
include $(BASE)/build/generic.mk
