#!/bin/bash

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net --recv-key 0xB01FA116
sudo apt-get update

sudo apt-get install \
ros-indigo-desktop \
ros-indigo-object-recognition-ros-visualization \
ros-indigo-object-recognition-tabletop \
ros-indigo-baxter-core-msgs \
ros-indigo-pr2-mechanism-msgs