#! /bin/sh

## parameters for this install
MLR_LIBPATH=/home/lib
MLR_URL=http://userpage.fu-berlin.de/mtoussai/smScpB076X

if [ ! -d $MLR_LIBPATH ] ; then
  echo "Creating lib directory: " $MLR_LIBPATH
  sudo mkdir $MLR_LIBPATH
  sudo chown $(id -u) $MLR_LIBPATH
  sudo chgrp $(id -u) $MLR_LIBPATH
fi

# install ubuntu packages
sudo apt-get install \
bison \
build-essential \
doxygen \
flex \
freeglut3-dev \
g++ \
gcc \
gfortran \
git-core \
gnuplot \
graphviz-dev \
libann-dev \
libcv-dev \
libcvaux-dev \
libdc1394-22-dev \
libf2c2-dev \
libgl1-mesa-dev \
libgl1-mesa-glx \
libglu1-mesa \
libglu1-mesa-dev \
libgtkglext1-dev \
libhighgui-dev \
liblapack-dev \
libplib-dev \
libqhull-dev \
libsdl1.2-dev \
libx11-dev \
libx11-dev \
libxi-dev \
libxmu-dev \
make \
meld \
realpath \
regexxer \
tcl8.5-dev \
tk8.5-dev

#install external libraries
./PHYSX_install
./ODE_install
#./IBDS_install
