#! /bin/sh

## parameters for this install
MLR_LIBPATH=/home/lib

if [ ! -d $MLR_LIBPATH ] ; then
  echo "Creating lib directory: " $MLR_LIBPATH
  sudo mkdir $MLR_LIBPATH
  sudo mkdir $MLR_LIBPATH/lib
  sudo chown $(id -u) $MLR_LIBPATH
  sudo chgrp $(id -u) $MLR_LIBPATH
  sudo chown $(id -u) $MLR_LIBPATH/lib
  sudo chgrp $(id -u) $MLR_LIBPATH/lib
fi

# install ubuntu packages
sh INSTALL_ALL_UBUNTU_PACKAGES.sh

#install external libraries
./PhysX_install
./ODE_install
#./IBDS_install

# install google test
cd /usr/src/gtest
sudo cmake .
sudo make
#sudo ln -s -f /usr/src/gtest/libgtest.a /home/lib/lib/
