#!/bin/bash

synaptic \
qtcreator \


libgtkglext1-dev \
libgtest-dev \
tcl8.5-dev \
tk-dev \
tk8.5-dev \

libqt4-dev-bin \

libdc1394-22-dev \
libavcodec-extra-53 \
libavcodec-extra-54 \
libavdevice-dev \
libavfilter-dev \
libx264-dev \

libsdl1.2-dev \
