#! /bin/sh

# Fail early. Abort on any error!
set -e

## parameters for this install
FILE=ode-0.11.tar.gz
SRC_PATH=ode-0.11
URL='https://mlr-owncloud.informatik.uni-stuttgart.de/public.php?service=files&t=c55ce4f1ee54e4da95aa8eaa5ea48b02&download'
THIS_PATH=$PWD

[ -z $MLR_LIBPATH ] && MLR_LIBPATH=/home/lib

echo "*** Installing" $SRC_PATH "into" $MLR_LIBPATH
echo

## download
echo -n "  * Checking for file" /tmp/$FILE "-> download"
read -p " -- [Enter] to continue..." yn
if [ ! -f /tmp/$FILE ] ; then
  wget -O /tmp/$FILE $URL --no-check-certificate
  if [ ! -f /tmp/$FILE ] ; then
    echo "Automatic Download failed. You need to download " $URL " and store it in " /tmp/$FILE
    exit
  fi
fi

## check existance of lib path
echo -n "  * Checking for directory" $MLR_LIBPATH
read -p " -- [Enter] to continue..." yn
if [ ! -d $MLR_LIBPATH ] ; then
  # only root can create the folder in /home
  sudo mkdir -p $MLR_LIBPATH
  # but everybody needs access to /home/lib
  sudo chmod o+r+w+x $MLR_LIBPATH
  # and also /home/lib/lib
  mkdir -p $MLR_LIBPATH/lib
fi

## delete & unpack
echo -n "  * Delete" $MLR_LIBPATH/src/$SRC_PATH "and unpack" /tmp/$FILE "?"
read -p " -- y/[n] ?" yn
case $yn in
    y|Y)
	mkdir -p $MLR_LIBPATH/src
	cd $MLR_LIBPATH/src
	rm -Rf $SRC_PATH
	tar xvzf /tmp/$FILE
	;;
    *) ;;
esac

## make
echo -n "  * Compiling in" $MLR_LIBPATH/src/$SRC_PATH
read -p " -- [Enter] to continue..." yn
cd $MLR_LIBPATH/src/$SRC_PATH
sh autogen.sh
#./configure --help
./configure --prefix=$MLR_LIBPATH --enable-double-precision --with-trimesh=opcode --with-pic
make -j2
make install

## install
echo -n "  * Copying additional headers to" $MLR_LIBPATH/include/ode/internal
read -p " -- [Enter] to continue..." yn
cd $MLR_LIBPATH
mkdir -p include/ode/internal include/ode/internal/joints
cp src/$SRC_PATH/ode/src/*.h include/ode/internal
cp src/$SRC_PATH/ode/src/joints/*.h include/ode/internal/joints

## clean
echo -n "  * Make clean in" $MLR_LIBPATH/src/$SRC_PATH
read -p " -- [Enter] to continue..." yn
cd $MLR_LIBPATH/src/$SRC_PATH
find . -name '*.o' -delete
