BASE = ../..


FREEGLUT = 1
SWIFT = 1
LAPACK = 1
BUMBLE = 1
VISION = 1
SCHUNK = 1
PLIB = 1  #for the Joystick
STANIMIR = 1
LEWINER = 1
#REVEL = 1

CXXFLAGS += -DMT_Lewiner

include $(BASE)/make-generic

