BASE = ../../../share

OPENCV=1

CXXFLAGS += -I/opt/XIMEA/include -DMT_IMPLEMENT_TEMPLATES
LPATHS += /opt/XIMEA/lib

LIBS += -lXIMEA_GenTL

# ffmpeg stuff
#CXXFLAGS += -D__STDC_CONSTANT_MACROS
#LIBS += -lavutil -lavcodec -lavformat -lavdedice -lswscale

include $(BASE)/gofMake/make-generic
