BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT := $(BASE)/lib/$(NAME).so _swig.so

ROS = 1

DEPEND = pr2 Motion Ors Core Control FOL Hardware Perception Hardware_gamepad Gui Media

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
