BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = ../$(NAME).so swig_wrap.cxx _swig.so

ROS = 1

DEPEND = RosCom Motion Ors Core Control FOL Hardware Perception Hardware_gamepad Gui Media

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/build/generic.mk
