BASE = ../..

OBJS = main.o puppeteer.o
PLIB = 1
DEPEND = Core System Hardware Hardware_joystick Motion Ors Gui System System_ros

LPATHS += /opt/ros/groovy/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/gofMake/generic.mk
