BASE = ../..

OBJS = main.o src/task_door.o src/traj_factory.o src/plotUtil.o
DEPEND = Core Ors Gui Algo Motion Optim System pr2 Hardware_gamepad Actions
PTHREAD = 0
PHYSX = 0

include $(BASE)/gofMake/generic.mk
