BASE = ../..

OBJS = main.o src/task_door.o src/traj_factory.o src/plotUtil.o src/functional.o src/motion_interface.o
DEPEND = Core Kin Gui Algo KOMO Optim RosCom
PTHREAD = 0
PHYSX = 0
QHULL = 1
include $(BASE)/build/generic.mk
