option(USE_FLTK "Use FLTK" OFF)
if(USE_FLTK)
        set(MT_FLTK -DMT_FLTK)
endif(USE_FLTK)
option(USE_GTKGL "Use GTK GL" ON)
if(USE_GTKGL)
        set(MT_GTKGL -DMT_GTKGL)
        set(USE_GL ON)
endif(USE_GTKGL)
option(USE_FREEGLUT "Use FreeGLUT" OFF)
if(USE_FREEGLUT)
        set(MT_FREEGLUT -DMT_FREEGLUT)
        set(USE_OPENGL ON)
endif(USE_FREEGLUT)
option(USE_OPENGL "Use OpenGL" ON)
if(USE_OPENGL)
        set(MT_GL -DMT_GL)
endif(USE_OPENGL)

