BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = $(BASE)/lib/$(NAME).so
-include $(BASE)/gofMake/config.mk

GL = 1
GTK = 1
GTKGL = 0
FREEGLUT = 0
GRAPHVIZ = 1

DEPEND = Core Geo

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
