BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT = ../$(NAME).so

DEPEND = Core Infer Gui

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/build/generic.mk
