set(SOURCES ./pradaBackwards.h
./pradaBackwards.cpp
./symbols.h
./relevanceGrounding.cpp
./ppddl.cpp
./robotManipulationInterface.h
./reason_rules.cpp
./utilTL.h
./prada.cpp
./ruleLearner_ground.h
./learn_searchOperators.cpp
./symbolGrounding.h
./reason.cpp
./literals.cpp
./robotManipulationSymbols.cpp
./explore.cpp
./decisionMakingModule.cpp
./robotManipulationSymbols.h
./experiments_fixedContexts.cpp
./decisionMakingModule.h
./conceptLearner.cpp
./learn.h
./learn.cpp
./symbols.cpp
./ruleLearner_ground.cpp
./plan.h
./robotManipulationInterface.cpp
./utilTL.cpp
./rules.cpp
./robotManipulationSimulator.cpp
./reason.h
./robotManipulationSimulator.h
./ppddl.h
./plan.cpp
./literals.h
./symbolGrounding.cpp
./prada.h
./relevanceGrounding.h
./conceptLearner.h
./explore.h
./experiments_fixedContexts.h
./rules.h)
