BASE   = ../..
NAME   = lib$(shell basename `pwd`)
OUTPUT := $(BASE)/lib/$(NAME).so

-include $(BASE)/gofMake/config.mk
ifeq ($(PURE_RELATIONAL),1)
DEPEND = Core
else
DEPEND = Core Ors Gui Motion
endif

SRCS = $(shell find . -maxdepth 1 -name '*.cpp' )
OBJS = $(SRCS:%.cpp=%.o)

include $(BASE)/gofMake/generic.mk
