BASE = $(shell pwd)/../..

OPTIM = debug

OBJS = main.o $(BASE)/src/MT/vision_cuda.o

LAPACK = 1
OPENCV = 1
FELZ = 1
VISION = 1
FREEGLUT=1
QHULL = 1
ESS = 1
BUMBLE = 1
#NILS = 1
CUDA = 1

include $(BASE)/make-generic
