BASE = ../..
OBJS = main.o

OBJS = 	main.o \
	$(BASE)/src/MT/vision_cuda.o

CXXFLAGS += -DMT_IMPLEMENTATION

#MTLIB = 1

ANN = 1
#TONY = 1
OPENCV = 1
SCHUNK = 1
#ODE = 1
QHULL = 1
FREEGLUT = 1
SWIFT = 1
LAPACK = 1
PLIB = 1
BUMBLE = 1
#URGLASER = 1
CUDA = 1
#REVEL = 1
LEWINER = 1
NIKOLAY = 1
TOBIAS = 1
NILS = 1

include $(BASE)/make-generic

