BASE = ../..


OBJS = main.o
PLIB = 1
ROS = 1
ROS_VERSION=groovy
DEPEND = Core KOMO Kin Gui RosCom Optim Algo

LPATHS += /opt/ros/groovy/lib

#CXXFLAGS += -DROS_PACKAGE_NAME='"pr2_module"'

include $(BASE)/build/generic.mk
