BASE = $(shell pwd)/../../../share
OBJS = main.o

# OPTIM = fast
OPTIM = debug

TOBIAS = 1

# FREEGLUT= 1
ODE	= 1
SWIFT	= 1
QHULL	= 1
# REVEL = 1

CXXFLAGS += -fPIC -DMT_IMPLEMENT_TEMPLATES #causes all *.cpp to implement the used templates

include $(BASE)/gofMake/generic.mk
