BASE = ../../../share

ROS = 1

#OBJS = main.o DynamicSimulation.o Controller.o PR2Interface.o

DEPEND = Core Hardware_gamepad Motion Kin Gui RosCom Optim Geo Algo Control

include $(BASE)/build/generic.mk
