BASE = ../../../..

PLIB = 1

OBJS =  calibrator_module.o
DEPEND = Core Mocap System Hardware_gamepad Hardware_G4 Motion Ors Perception

# comment/uncomment to disable/enable ROS
# ROS = 1
# ROS_VERSION = groovy
# CXXFLAGS = -DWITH_ROS
# DEPEND += pr2 Actions
# LPATHS += /opt/ros/groovy/lib

include $(BASE)/gofMake/generic.mk
