BASE = ../../../..

PLIB = 1

OBJS =  calibrator_module.o
DEPEND = Core Mocap System Hardware_gamepad Hardware_G4 KOMO Kin Perception

# comment/uncomment to disable/enable ROS
# ROS = 1
# ROS_VERSION = groovy
# CXXFLAGS = -DWITH_ROS
# DEPEND += RosCom Actions
# LPATHS += /opt/ros/groovy/lib

include $(BASE)/build/generic.mk
