BASE = ../..

OBJS = main.o sim.o komo_fine.o filter.o

PLIB = 1
ROS = 1
PCL = 1
GL = 1
DEPEND = Core RosCom Control Gui Hardware_gamepad Kin KOMO Geo Roopi Perception PCL Algo

include $(BASE)/build/generic.mk
