BASE = ../../..

DEPEND = Core Gui Perception

CXXFLAGS += -D__STDC_CONSTANT_MACROS
LPATHS += /usr/local/lib
LIBS += -lavformat -lavcodec -lavutil -lswscale -lx264 -lz

include $(BASE)/gofMake/generic.mk
